modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="CC BY-NC-SA 4.0 IPL"
issueTrackerURL="http://github.com/itsmeow/QuickHomes/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/quickhomes" #optional
logoFile="quickhomes.png" #optional
credits="its_meow, for programming, ideas, design, and leading" #optional
authors="its_meow" #optional
[[mods]] #mandatory
modId="quickhomes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="QuickHomes" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod adds a quick and easy way to set homes with /sethome and /home'''
[[dependencies.quickhomes]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.62,)"
    ordering="NONE"
    side="BOTH"